#
#                    ##        .
#              ## ## ##       ==
#           ## ## ## ##      ===
#       /""""""""""""""""\___/ ===
#  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
#       \______ o          __/
#         \    \        __/
#          \____\______/
#
#          |          |
#       __ |  __   __ | _  __   _
#      /  \| /  \ /   |/  / _\ |
#      \__/| \__/ \__ |\_ \__  |
#

version: "3"


services:
# Application Container
  apps:
    image: kankuu/php5-laravel4
    container_name: absensi
    working_dir: /var/www/html/public
    ports:
        - "4505:80"
    volumes:
      - /aplikasi/absensi:/var/www/html/public
    network_mode: bridge